### ISSUE TITLE
Securing Resource

### ISSUE THREAD

**Issue by lukas-gitl** [wndhydrnt/python-oauth2#29]
How would I secure a restful access point (e.g. only allow access to it with a valid access token)?

**Comment by bhoomit** [comment]
I've been using openresty(nginx) with lua and redis to achieve this. 

This link can help you get started: http://tech.3scale.net/2013/01/09/augment-your-api-without-touching-it/

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
