### ISSUE TITLE
Tornado example for oath2  does not work python3.4

### ISSUE THREAD

**Issue by XxxUNIXxxX** [wndhydrnt/python-oauth2#36]
1) Request not imported

**Comment by XxxUNIXxxX** [comment]
I tried http://python-oauth2.readthedocs.org/en/latest/tornado.html

**Comment by wndhydrnt** [comment]
Thinking about adding an Adapter that connects the library with Tornado.
It would be an alternative to the standard WSGI interface.

**Comment by wndhydrnt** [comment]
Should be fixed by merging #42.
