### ISSUE TITLE
Returned state token not url-encoded

### ISSUE THREAD

**Issue by espu** [wndhydrnt/python-oauth2#37]
Current implementation reads state from request query parameter with request.get_param(), which handles url-decoding automatically. When state is written back to a redirect url it is not url-encoded. This causes state mismatch in client. Only applies to clients that use state strings that yield are url-decodable.

Reproducable with /examples/authorization_code_grant.py, modifying ClientApplication.

Generate a state token in client:
```
def _request_auth_token(self):
        print("Requesting authorization token...")
        auth_endpoint = self.api_server_url + "/authorize"
        self.state = "123123%25"
        query = urllib.urlencode({"client_id": "abc",
                                  "redirect_uri": self.callback_url,
                                  "response_type": "code",
                                  "state":self.state,
                                  })

        location = "%s?%s" % (auth_endpoint, query)
```

And check state when receiving token:
```
def _read_auth_token(self, env):
    print("Receiving authorization token...")

    query_params = urlparse.parse_qs(env["QUERY_STRING"])
    self.auth_token = query_params["code"][0]
    
    if self.state and self.state != query_params["state"][0]:
        raise Exception("Received auth token with invalid state. If this was a browser, CSRF")
```   

Fix by url-encoding the state when applying it to redirect urls.
/oauth2/grant.py
```
469      query += "&state=" + quote(self.state)

708      uri_with_fragment += "&state=" + quote(self.state)

**Comment by wndhydrnt** [comment]
I checked the [RFC](https://tools.ietf.org/html/rfc6749#appendix-A.5) and indeed the state parameter can contain characters that should be urlencoded.
Great that you found this, I totally missed it.
