### ISSUE TITLE
New parameter client 

### ISSUE THREAD

**Issue by viniciuschiele** [wndhydrnt/python-oauth2#41]
**AuthenticatingSiteAdapter.authenticate** and **UserFacingSiteAdapter.render_auth_page** could have a parameter to receive the client retrieved from the store.

In my case, my client table has extra columns that I need to render the authentication page, If I had access to the client object it would be easier. 

Thanks!

**Comment by wndhydrnt** [comment]
This shouldn't do any harm and I'll add it as soon as I find the time.
