### ISSUE TITLE
Redis fetch_by_token

### ISSUE THREAD

**Issue by hyacinthus** [wndhydrnt/python-oauth2#49]
Hello,
  I find a function "fetch_by_token" in oauth2.store.memory.TokenStore , but in the Base Class and the redis.TokenStore Class I can't find this one.

  I use the Resource Owner Grant model , the client request send the token by HTTP haeder Authorization. Shoud I write a fetch_by_token function by myself, or let the client send me both user_id and token?

Thanks

**Comment by hyacinthus** [comment]
And the scope part is not easy to use...

**Comment by wndhydrnt** [comment]
The `fetch_by_token` method has been written to [aid a unit test](https://github.com/wndhydrnt/python-oauth2/blob/master/oauth2/test/store/test_memory.py#L62). If you need such a method in `oauth2.store.redisdb.TokenStore`, I'd suggest extending the class and adding it in your codebase.

Could you provide a bit more detail on the "scope not easy to use" part? It's a bit hard to infer any actions from it.

**Comment by hyacinthus** [comment]
Hey, I'm a newbie in working with oauth2. So If there is not a fetch_by_token function, I'll think why should I need it? Is my authorization flow incorrect? ...
Could you tell me how to identify a token in request header is legitimate?

About scope...Let me think twice

**Comment by wndhydrnt** [comment]
Do you mean a request to the backend server of your application?
In that case there are lots of ways to validate the token:
* You could configure python-oauth2 to store access tokens in [memcache](https://github.com/wndhydrnt/python-oauth2/blob/master/oauth2/store/memcache.py). Then read from memcache in your app. You can make use of [decorators](http://simeonfranklin.com/blog/2012/jul/1/python-decorators-in-12-steps/) to create a wrapper and avoid repetition.
* If you use nginx as a loadbalancer in front of your backend servers, you can write a lua script that reads the token from memcache and declines access if it cannot find the token.

**Comment by hyacinthus** [comment]
Yes, I want to validate the token in my backend server.
I use redis to store the token.
I do write a decorator, then I found I can't get the oauth data just by token.
Do you mean your oauth2 module only used as a authorization server ,but not a backend app validator?

Thanks for your advise about nginx, it's a nice idea. I'll try it.

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
