### ISSUE TITLE
Upgrade PyPI version

### ISSUE THREAD

**Issue by stgleb** [wndhydrnt/python-oauth2#54]
Hello,
i'm using you library python-oauth2==1.0.0 in my project,
but could you please upgrade version available on pypi to 1.0.0 version.
it will be very helpful for Continous integration in my project.
because on local machine i've installed it with setup.py from sources on github.

Thanks.

**Comment by wndhydrnt** [comment]
Thanks for reminding me of this. The new release is published on PyPi.
