### ISSUE TITLE
Redis lack of memory

### ISSUE THREAD

**Issue by stgleb** [wndhydrnt/python-oauth2#56]
Hello, i'm using your library to establish oauth2 server. But recently on stage of load testing i've
found that server returns 400 Bad request when i', trying to refresh token. I use redis as a storage for tokens. I have a hypothesis that lack of memory could be a reason.
    Actually server that i use have not enough memory righ now and only the small part is occupied by redis.
free -h output

Total       used       free     shared    buffers     cached
Mem:          993M       902M        91M       144K        54M       128M
-/+ buffers/cache:       719M       274M
Swap:         1.0G        71M       949M

So how do you this is this behavoir expected for your lib when it uses redis and doesnt have enough memory?

**Comment by wndhydrnt** [comment]
Honestly, there is no behaviour that could be called "expected" if a system is running out of memory.
However the output of `free` shows that there is still `274M` of freeable memory.
Could you provide more information on your test setup? How do you invoke the library? Which HTTP server do you use? How many requests are being sent per second?
Also the memory usage of the processes involved, Oauth2 server and redis, would be nice to know.
Please provide the output of
```
echo 0 $(awk '/Pss/ {print "+", $2}' /proc/`pidof PROCESS`/smaps) | bc
```
(per http://stackoverflow.com/a/3854444)

**Comment by stgleb** [comment]
Sorry, it seems that i've screwed up by using very short refresh_token expiration time, so my users wre logged out innermously. I thought it was a problem in redis, but seems not.

**Comment by wndhydrnt** [comment]
Alright, thanks for the feedback. Closing this.

**Comment by stgleb** [comment]
But i still have got a problem, not very often, but server returns 400 Bad request when i'm trying to refresh access token using it refresh. It happens now often so i cannot reproduce it and debug. I have
refresh token reissue property and actually lifespan of refresh token is one year(365 * 24 * 60 * 60). Whan can be a reason of that? 
P.S i'm using mongo db as a storage backend right now.
