### ISSUE TITLE
URI decoding and encoding modifies state variable

### ISSUE THREAD

**Issue by SumnerH** [wndhydrnt/python-oauth2#62]
We have a client who's sending us a state variable of the form "https%3a%2f%2f...".  This is legal as far as I can tell.  But if it's URI-decoded and then re-encoded (which is how oauth2 works now), then the python urllib2.quote function encodes it to "https%3a//...".   

That is a valid URI-encoding, but the oauth2 documentation says that "The authorization server must return the unmodified state value back to the application."  

The central problem is that URI-decoding and then URI-encoding a string is not an identity function, because there are multiple valid encodings of the same string.

I believe the only way to preserve the unmodified state value is twofold:
1. The oauth2 server must never URI-decode the state variable that the client passes in (once decoded, there's no way to recover which encoded form the client passed in).
2. The oauth2 library therefore should not URI-encode the state variable in grant.py (definitely in _generate_location, and also in _redirect_access_token I believe but I haven't tested the latter).

Obviously this change could break a lot of existing implementations that use URI-decoded variables, so it should probably be a flag/setting of some sort.  

Right now I'm monkey-patching _generate_location to work around this.

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
