### ISSUE TITLE
cannot use POST to confirm

### ISSUE THREAD

**Issue by minrk** [wndhydrnt/python-oauth2#64]
The docs include this example:

```python
# Create a SiteAdapter to interact with the user.
# This can be used to display confirmation dialogs and the like.
class ExampleSiteAdapter(oauth2.web.AuthorizationCodeGrantSiteAdapter,
                         oauth2.web.ImplicitGrantSiteAdapter):
    def authenticate(self, request, environ, scopes, client):
        # Check if the user has granted access
        if request.post_param("confirm") == "confirm":
            return {}

        raise oauth2.error.UserNotAuthenticated

    def render_auth_page(self, request, response, environ, scopes, client):
        response.body = '''
<html>
    <body>
        <form method="POST" name="confirmation_form">
            <input type="submit" name="confirm" value="confirm" />
            <input type="submit" name="deny" value="deny" />
        </form>
    </body>
</html>'''
        return response
```

which suggests that you can use POST to the authorize URL to set the confirm/deny state. This does not work right now because the AuthorizationCodeGrant explicitly checks if the method is GET before dispatching to the AuthorizationCodeAuthHandler, so it will always fail with:

```json
{
"error": "unsupported_response_type",
"error_description": "Grant not supported"
}
```

To reproduce the error, run the example on the front page of [the docs](http://python-oauth2.readthedocs.io/en/latest/).

**Comment by wndhydrnt** [comment]
Thanks for the issue @minrk. I searched through the commits and identified https://github.com/wndhydrnt/python-oauth2/commit/bb9bffefb4dc57a8eecc695bd0a3dcb9591634f8 as the commit that broke the code in the example. I think the example should be rewritten. I'll think of a new version.

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
