### ISSUE TITLE
User_id and ImplicitGrantHandler

### ISSUE THREAD

**Issue by marbex7** [wndhydrnt/python-oauth2#65]
This is not a bug report. It is a request to help understand correct usage of the library.

When the access_token object is created in the ImplicitGrant flow:
https://github.com/wndhydrnt/python-oauth2/blob/v1/oauth2/grant.py#L698
the user_id is not captured/populated.

I thought that when my API server receives a bearer token, I would be able to query the token store and use the user_id field of the returned AccessToken data to populate the REMOTE_USER request variable.

In my python-oauth2 server I have been able to add the user_id (which I capture at the authenticate step) as "additional data". But it puzzled me (I am not an expert in this area) that the AccessToken class has a field for user_id which is not used when instantiation occurs in the ImplicitGrant flow.

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
